-- ============================================================================
--  exmsys · 心理咨询师考试背题系统
--  云端 PostgreSQL 建库脚本（Supabase / Neon / Aiven 通用）
--                                          文件：01_schema.sql
-- ----------------------------------------------------------------------------
--  来源   ：本地 SQLite 库 data/exmsys.db 的结构快照（2026-10-08 导出）
--  执行   ：云端控制台的 SQL Editor -> 【整段一次性】粘贴 -> Run（三家都一样）
--           ⚠️ Neon / Aiven 请用【直连】端点执行，不要用连接池端点（-pooler / 非 5432 端口）：
--              连接池是 PgBouncer transaction 模式，不支持会话级语义，DDL 可能中途失败。
--  目标库 ：独立 schema `psych_exm`（不是 public）—— 见下面第 0 节
--  幂等性 ：全部使用 create table if not exists / 可重复执行，重跑不报错
--  平台差异：仅第 6 节的 anon / authenticated 授权回收是 Supabase 专属，
--           脚本内已做角色存在性判断，其他平台自动跳过。
-- ----------------------------------------------------------------------------
--  设计原则（重要，别改）
--  1) 表名 / 列名 / 列语义与 SQLite 版【逐字一致】，不做任何重命名，
--     这样数据访问层（utils/data_access.py）只需换连接与方言，页面层零改动。
--  2) 类型映射约定：
--       TEXT                              -> text
--       INTEGER                           -> integer
--       INTEGER PRIMARY KEY AUTOINCREMENT -> bigint generated by default as identity
--       REAL                              -> double precision
--  3) 所有日期时间字段【保持 text】。库里存的是 Python 侧生成的 ISO 字符串，
--     换成 timestamptz 会引入时区与格式转换，反而破坏与现有代码的兼容。
--  4) is_correct / last_correct / unstable / is_case_background 等【保持 integer】
--     而不是 boolean：现有代码读写的是 0/1，换 boolean 必须改 SQL，得不偿失。
--  5) 公共题库 owner 仍用哨兵值 '__public__' 而不是 NULL ——
--     PostgreSQL 与 SQLite 一样「NULL 互不相等」，若用 NULL，
--     UNIQUE(owner_id, md5) 会直接失效（公共题库去重坏掉）。
-- ============================================================================


-- ============================================================================
--  0. 目标 schema —— 要改就只改这一节（共 3 处字面量）
-- ----------------------------------------------------------------------------
--  为什么用独立 schema：一个 Supabase 项目 = 一个 PostgreSQL 实例，实例里可以建
--  任意多个 schema。本实例的 public 已被【另一个应用】占用，所以本项目放到
--  独立的 psych_exm 里：两边表名互不干扰（users / drafts 这类名字两边都可能存在）、
--  权限各自独立、备份恢复时也不会互相覆盖。
--
--  额外好处（Supabase 官方文档已确认）：自建的 schema 默认**不在
--  API Settings -> Exposed schemas 列表里**（默认只有 public / graphql_public），
--  因此它根本不会出现在 Data API 上 —— 别人拿着本项目的 anon key 也触不到这些表。
--  ⚠️ 所以：**不要**把 psych_exm 加进 Exposed schemas。
--  注意区分：表里的 owner_id = '__public__' 是【数据层的哨兵值】，与本节的
--  数据库 schema（命名空间）是两回事，别混淆。
--
--  ⚠️⚠️ 本脚本依赖下面的 `set search_path`：第 1~7 节所有表名都是**不带前缀的裸名**。
--      因此必须【整段一次性执行】：
--        · 控制台 SQL Editor 全文粘贴 → Run                              ✔ 正确
--        · 逐条选中执行                                                    ✘ 错误
--      因为逐条执行时每条语句是独立会话，set search_path 会丢失，
--      紧接着的断言块会**立刻报错中止** —— 宁可报错，也绝不把表静默建到 public 里
--      去污染另一个应用（那是这个设计里最致命的失败模式）。
--
--  要换 schema 名：改下面这 3 处（create / set / 断言里的字符串）即可，
--  第 1~8 节全部用 current_schema() 或裸名，不需要再改。
-- ============================================================================

create schema if not exists psych_exm;

set search_path to psych_exm;

do $$
begin
    if current_schema() <> 'psych_exm' then
        raise exception
            'search_path 未生效：当前解析到 schema = %。本脚本必须【整段一次性执行】，'
            '逐条执行会丢失 set search_path，导致表被建到错误的 schema 里。',
            current_schema();
    end if;
end $$;


-- ============================================================================
--  1. 身份：用户 / 设备
-- ============================================================================

create table if not exists users (
    user_id        text primary key,
    username       text unique,
    password_hash  text,
    role           text not null default 'user',
    display_name   text,
    created_at     text,
    last_login     text
);
comment on table  users            is '用户账号。user_id = md5("exmsys_device_" + 设备指纹)[:12]（兼容性契约，不得更改）';
comment on column users.role       is '角色：admin / user';
comment on column users.username   is '登录名；未设账号的用户为 NULL（PostgreSQL 与 SQLite 一样允许多行 NULL）';

create table if not exists user_devices (
    device_fp  text primary key,
    user_id    text not null,
    first_seen text,
    last_seen  text
);
comment on table user_devices is '设备指纹 -> 用户 的绑定关系（免登录自动识别设备）';


-- ============================================================================
--  2. 配置：全局 / 用户级
-- ============================================================================

create table if not exists app_config (
    key   text primary key,
    value text
);
comment on table app_config is '全局配置（所有用户共享）。例：_questions_data_version 题库数据版本号';

create table if not exists user_config (
    user_id text not null,
    key     text not null,
    value   text,
    primary key (user_id, key)
);
comment on table user_config is '用户级配置。value 为 JSON 文本（如 retention_days_threshold）';


-- ============================================================================
--  3. 题库：题目 / 案例背景
-- ============================================================================

create table if not exists questions (
    id                 text primary key,
    owner_id           text not null default '__public__',
    source_file        text,
    index_num          integer,
    type               text not null,
    question           text not null,
    options            text not null,
    answer             text not null,
    explanation        text,
    md5                text not null,
    category           text,
    exam_type          text,
    case_study_id      text,
    is_case_background integer default 0
);
comment on table  questions            is '题目主表。owner_id = ''__public__'' 为公共题库（仅管理员可改），否则为该用户的私人题库';
comment on column questions.id         is '题目稳定 ID = md5("owner|题干+选项+答案")[:12]，一经分配永不变更';
comment on column questions.type       is '题型：single / multi / judge / indefinite / 案例题';
comment on column questions.options    is '选项 JSON 文本，如 {"A": "...", "B": "..."}';
comment on column questions.md5        is '题干+选项+答案 的内容指纹。注意：历史上有约 2417/5118 条与内容不一致，配对时必须两侧现算，不能拿它当准';
comment on column questions.case_study_id is '所属案例 ID（关联 case_studies.id）；非案例题为空字符串';
comment on column questions.is_case_background is '1 表示该行只是案例背景文本，不参与做题';

create table if not exists case_studies (
    id              text primary key,
    owner_id        text not null default '__public__',
    title           text,
    background_id   text not null default '',
    question_count  integer default 0,
    exam_type       text
);
comment on table  case_studies      is '案例背景。背景正文存在 title 列（历史命名，勿改）';
comment on column case_studies.question_count is '该案例下的子题数量（缓存值，以 questions 表实际数据为准）';


-- ============================================================================
--  4. 学习数据：统计 / 错题 / 记录 / 草稿
-- ============================================================================

create table if not exists question_stats (
    question_id       text not null,
    user_id           text not null default '',
    correct_count     integer default 0,
    wrong_count       integer default 0,
    last_answer_time  text,
    last_correct      integer,
    answer_history    text,
    mastery_level     integer default 0,
    confidence        double precision default 0.0,
    unstable          integer default 0,
    self_uncertainty  double precision default 0.0,
    first_answer_time text,
    exam_type         text,
    primary key (question_id, user_id)
);
comment on table  question_stats     is '每题每人的掌握度统计。主键 (question_id, user_id)';
comment on column question_stats.mastery_level is '掌握度 0~5 级';
comment on column question_stats.answer_history is '答题历史 JSON 文本';
comment on column question_stats.unstable is '1 表示暂不稳固（巩固练习题源）';

create table if not exists wrong_questions (
    question_id text not null,
    user_id     text not null default '',
    exam_type   text,
    primary key (question_id, user_id)
);
comment on table wrong_questions is '错题本。主键 (question_id, user_id)';

create table if not exists answer_records (
    id           bigint generated by default as identity primary key,
    user_id      text not null default '',
    question_id  text not null,
    user_answer  text,
    is_correct   integer not null,
    mode         text,
    session_id   text,
    category     text,
    timestamp    text not null,
    exam_type    text
);
comment on table  answer_records       is '逐题答题流水。全项目无代码引用其自增 id（仅用于排序/审计），故合并重编号无副作用';
comment on column answer_records.timestamp is 'ISO 字符串，不是 timestamptz（见文件头设计原则 3）';

create table if not exists exam_records (
    id        bigint generated by default as identity primary key,
    user_id   text not null default '',
    data      text not null,
    exam_type text
);
comment on table exam_records is '普通考试（专项/综合）结果，data 为 JSON 文本';

create table if not exists mock_exam_records (
    id        bigint generated by default as identity primary key,
    user_id   text not null default '',
    data      text not null,
    exam_type text
);
comment on table mock_exam_records is '模拟考试结果，data 为 JSON 文本';

create table if not exists study_records (
    session_id text primary key,
    user_id    text not null default '',
    mode       text,
    total      integer,
    answered   integer,
    correct    integer,
    wrong      integer,
    start_time text,
    end_time   text,
    details    text,
    exam_type  text
);
comment on table study_records is '背题/学习会话记录';

create table if not exists drafts (
    id        text primary key,
    user_id   text not null default '',
    prefix    text not null,
    draft_id  text not null,
    data      text not null,
    saved_at  text not null,
    exam_type text
);
comment on table  drafts     is '答题草稿（断点续答）。id = "{user_id}|{prefix}|{draft_id}"';
comment on column drafts.data is '整份草稿的 JSON 文本';


-- ============================================================================
--  5. 索引（与 SQLite 版同名同列，便于对照排查）
-- ============================================================================

create index if not exists idx_questions_owner      on questions(owner_id);
create index if not exists idx_questions_exam_type  on questions(exam_type);
create index if not exists idx_questions_category   on questions(category);
create index if not exists idx_questions_type       on questions(type);
create index if not exists idx_questions_case       on questions(case_study_id);

-- 公共题库去重 / 私人题库去重都靠这个唯一索引，不要删！
create unique index if not exists uniq_questions_owner_md5 on questions(owner_id, md5);

create index if not exists idx_case_studies_owner   on case_studies(owner_id);

create index if not exists idx_question_stats_user      on question_stats(user_id);
create index if not exists idx_question_stats_exam_type on question_stats(exam_type);

create index if not exists idx_wrong_questions_user      on wrong_questions(user_id);
create index if not exists idx_wrong_questions_exam_type on wrong_questions(exam_type);

create index if not exists idx_answer_records_user      on answer_records(user_id);
create index if not exists idx_answer_records_qid       on answer_records(question_id);
create index if not exists idx_answer_records_session   on answer_records(session_id);
create index if not exists idx_answer_records_timestamp on answer_records(timestamp);
create index if not exists idx_answer_records_exam_type on answer_records(exam_type);

create index if not exists idx_exam_records_user      on exam_records(user_id);
create index if not exists idx_exam_records_exam_type on exam_records(exam_type);

create index if not exists idx_mock_exam_records_user      on mock_exam_records(user_id);
create index if not exists idx_mock_exam_records_exam_type on mock_exam_records(exam_type);

create index if not exists idx_study_records_user      on study_records(user_id);
create index if not exists idx_study_records_exam_type on study_records(exam_type);

create index if not exists idx_drafts_user   on drafts(user_id);
create index if not exists idx_drafts_prefix on drafts(prefix);

create index if not exists idx_user_devices_user on user_devices(user_id);


-- ============================================================================
--  6. 关闭 Data API 暴露（安全）
-- ----------------------------------------------------------------------------
--  背景：Supabase 会把 public 架构通过 PostgREST 以 anon / authenticated
--  密钥公开出去。本应用走的是【直连 Postgres】（psycopg2），自己用 user_id/owner_id
--  做隔离，根本不需要 PostgREST；若不加限制，任何人拿到项目里的 anon key
--  就能读写全部题库与用户数据。
--
--  注意：本项目用的是独立 schema（psych_exm），而 Supabase 的 PostgREST 默认
--  **只暴露 public / graphql_public** —— 也就是说 psych_exm 本来就不在
--  Data API 的可见范围里（前提：不要把它加进 Exposed schemas）。
--  本节属于【纵深防御】：万一以后有人误把 psych_exm 加进 Exposed schemas，
--  这里的 RLS + REVOKE 仍然挡得住。
--
--  做法：给目标 schema 下所有表开启 RLS 且【一条策略都不建】= 拒绝
--        anon/authenticated 的一切访问；同时收回表级 / 序列级 / schema 级权限。
--        应用连接用的角色是表 Owner，默认绕过 RLS，读写不受影响。
--
--  为什么全部用 current_schema() 拼 SQL 而不是写死 schema 名：
--    本文件第 0 节的 set search_path 已经把 current_schema() 锚定到 psych_exm，
--    这样换 schema 名时不必再回来改这一节。
--
--  ⚠️ 跨平台注意（Neon / Aiven / 自建 PostgreSQL）：
--     anon 与 authenticated 是【Supabase 内置角色】。其他平台没有这两个角色，
--     无条件 REVOKE 会抛 "role \"anon\" does not exist" 并中断整个脚本
--     （SQL Editor / psql 默认在错误处停止，后面的序列对齐和第 7 节就跑不到了）。
--     所以这里先查 pg_roles 判断角色存在才执行。
--     RLS 本身是原生 PostgreSQL 特性，各平台都能开；对没有 PostgREST 的平台
--     属于无害的额外加固（Owner 绕过，应用读写不受影响）。
-- ============================================================================

do $$
declare
    t            text;
    sch          text := current_schema();
    needs_revoke boolean;
    tbls text[] := array[
        'users', 'user_devices', 'app_config', 'user_config',
        'questions', 'case_studies', 'question_stats', 'wrong_questions',
        'answer_records', 'exam_records', 'mock_exam_records',
        'study_records', 'drafts'
    ];
begin
    -- 只有 Supabase 才有 anon / authenticated（PostgREST 的两个匿名角色）
    select exists (select 1 from pg_roles where rolname = 'anon')
       and exists (select 1 from pg_roles where rolname = 'authenticated')
      into needs_revoke;

    foreach t in array tbls loop
        execute format('alter table %I.%I enable row level security;', sch, t);
        if needs_revoke then
            execute format('revoke all on table %I.%I from anon, authenticated;', sch, t);
        end if;
    end loop;

    -- 序列权限一并收回（同样只在角色存在时执行）
    if needs_revoke then
        execute format(
            'revoke all on all sequences in schema %I from anon, authenticated', sch);
        -- schema 级 USAGE / CREATE 也收回：挡住"能进命名空间"这条路
        -- （表级 REVOKE 已经挡了数据访问，这里是第二道闸）
        execute format(
            'revoke all on schema %I from anon, authenticated', sch);
    end if;
end $$;


-- ============================================================================
--  7. 自增序列对齐（导入数据【之后】再执行，或直接跑 02_import 脚本自动完成）
-- ----------------------------------------------------------------------------
--  导入时是显式指定 id 灌入的，序列不会自动前进；不 setval 的话，
--  应用下一条 INSERT 会从 1 开始，直接主键冲突。
--
--  下面的表名是裸名，靠第 0 节的 set search_path 解析到 psych_exm。
--  若单独拷贝到新会话执行，会报 "relation does not exist" —— 这是刻意的：
--  报错比静默对齐到别的 schema 里的同名表安全得多。
-- ============================================================================

select setval(pg_get_serial_sequence('answer_records', 'id'),
              coalesce((select max(id) from answer_records), 1),
              (select max(id) from answer_records) is not null);
select setval(pg_get_serial_sequence('exam_records', 'id'),
              coalesce((select max(id) from exam_records), 1),
              (select max(id) from exam_records) is not null);
select setval(pg_get_serial_sequence('mock_exam_records', 'id'),
              coalesce((select max(id) from mock_exam_records), 1),
              (select max(id) from mock_exam_records) is not null);


-- ============================================================================
--  建库完成自检：应返回 13 行，每行 has_rls = t
--  schema_name 列应等于第 0 节设置的目标 schema（psych_exm）——
--  如果它显示 public，说明本脚本被逐条执行了，请重新整段执行。
-- ============================================================================

select current_schema()                                       as schema_name,
       c.relname                                              as table_name,
       c.relrowsecurity                                       as has_rls,
       (select count(*) from pg_index i
         where i.indrelid = c.oid and i.indisprimary)          as pk_count
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
 where n.nspname = current_schema()
   and c.relkind = 'r'
   and c.relname in ('users','user_devices','app_config','user_config',
                     'questions','case_studies','question_stats','wrong_questions',
                     'answer_records','exam_records','mock_exam_records',
                     'study_records','drafts')
 order by c.relname;


-- ============================================================================
--  类型约定守卫：本 schema 里不得存在 boolean 列
--
--  SQLite 用 INTEGER 存布尔（True / False 落库就是 1 / 0），PG 侧的表结构
--  逐字照搬 SQLite，所以整库靠 integer 模拟布尔、一个 boolean 列都没有。
--  方言层 utils/data_access_pg.py 的 _normalize_params() 会把 Python bool
--  统一归一成 0/1 再交给驱动 —— 依据正是「这一侧没有 boolean 列」。
--  一旦这里混进 boolean 列，归一化反而会让它写不进去（0/1 不是 boolean）。
--
--  背景（2026-10-09 真实事故）：question_stats.unstable / last_correct 收到
--  Python bool 时报 DatatypeMismatch: column "unstable" is of type integer
--  but expression is of type boolean —— PG 不做 boolean → integer 隐式转换。
--
--  注：DO 块里的 plpgsql 局部变量（如第 6 节的 needs_revoke boolean）
--      是过程变量、不属于任何表，不会出现在 information_schema.columns 里。
-- ============================================================================

do $$
declare
    bad text;
begin
    select string_agg(table_name || '.' || column_name, ', ')
      into bad
      from information_schema.columns
     where table_schema = current_schema()
       and data_type = 'boolean';

    if bad is not null then
        raise exception
            '目标 schema 里出现了 boolean 列：%。SQLite 用 INTEGER 存布尔，'
            'PG 侧必须逐字一致，否则方言层的 bool 归一化会失效。', bad;
    end if;
end $$;
